### ISSUE TITLE
Git workflow for Chadev

### ISSUE THREAD

**Issue by vendion** [chadev/Chadev-issues#4]
I don't know if everyone has a preferred way of working with Git and branching models, or if we really need one.  Personally I am a fan of [Gitflow style](http://nvie.com/posts/a-successful-git-branching-model/) workflow.

**Comment by kylegordy** [comment]
Thanks for bringing this up, I'm game with a Gitflow style workflow. I think it could really help us not step on each others toes when working on new features.

**Comment by vendion** [comment]
Yeah that is the point of it, there is also a [wrapper](https://github.com/nvie/gitflow) around Git that makes Gitflow easier, and BitBucket's Sourcetree(?) understands Git flow as well.  Personally I don't like those abstraction layers, but it may be helpful to some.

**Comment by kylegordy** [comment]
Yeah, I don't either. But yeah it might be helpful for some ;)

**Comment by acedrew** [comment]
@vendion or @kylegordy Since you both seem familiar with this, can you go ahead and create the skeletal branches? I was about to do it but thought I might screw it up unconsciously due to my unfamiliarity with the process. I'll start the profiles feature branch if you get the develop/etc stuff set up.  
I have the necessary config.yml changes done locally, just need a place to put them :)

**Comment by vendion** [comment]
The only branches that should ever be on GitHub is Master (the Live version
of the site) and develop.  From there each dev makes a "feature" branch
locally.  So you would fork develop and create a branch called something
like "feature-dev-page" where you would make the dev page that parses the
flat files to display.  Once you have that done you would merge into
develop and push it so we all can see.

**Comment by vendion** [comment]
Develop branch created

**Comment by kylegordy** [comment]
@acedrew Awesome, thanks for getting it started :+1:
